version: '2'
networks:
  default:
    external:
      name: ggggg
services:
  php:
    build: .
    container_name: testerdemo_php_1
    image: tester:70
    privileged: false
    restart: unless-stopped
    tty: true
    volumes: 
      - .:/var/www/html
    ports:
      - 80
  php71:
    build: ci/php71
    image: tester:71
    privileged: false
    restart: unless-stopped
    tty: true
    volumes: 
      - .:/var/www/html
    ports:
      - 80
  php72:
    build: ci/php72
    image: tester:72
    privileged: false
    restart: unless-stopped
    tty: true
    volumes: 
      - .:/var/www/html
    ports:
      - 80
