version: '2'
networks:
  default:
    external:
      name: ggggg
services:
  php56:
    build: .
    image: tester:70
    privileged: false
    restart: unless-stopped
    tty: true
    volumes: 
      - .:/var/www/html
    ports:
      - 32768:80